### PR TITLE
Added support for 128x128 screens in the SH1107 driver

### PR DESCRIPTION
**Pull request by QuicksandDesignStudio**
Small update to the sh1107 driver (luma/oled/device/__init__.py). Added support for 128 x 128 screens by including 
`(128, 128): dict(multiplex=0x7F, displayoffset=0x00) `
in the settings dict in the sh1107 object. This adds support for oleds like this one - https://www.adafruit.com/product/5297

multiplex and displayoffset values from Adafruit's library here https://github.com/adafruit/Adafruit_CircuitPython_DisplayIO_SH1107

SH1107 datasheet here
https://cdn-shop.adafruit.com/product-files/5297/SH1107V2.1.pdf

### CODE REVIEW

**Comment by QuicksandDesignStudio** [comment]
Apologies for the commit with trailing whitespaces. Removed.

**Review by thijstriemstra — CHANGES_REQUESTED** [review]
thanks! can you add:

-  your name to CONTRIBUTORS.rst
- the datasheet pdf to `doc/tech-spec`

**Comment by QuicksandDesignStudio** [comment]
> 

Done!

**Review by thijstriemstra — APPROVED** [review]
thanks!

**Pull request merged**
