### PR TITLE
Added support for 128x128

### PR DESCRIPTION
**Pull request by Gadgetoid**
Tested with a 128x128 SH1106.

### CODE REVIEW

**Comment by thijstriemstra** [comment]
thanks @Gadgetoid. can you 

- also add your name to CONTRIBUTING.rst in this pull request?
- make sure this does not break existing tests (run `tox`)
- try to add a test for this

**Comment by rm-hull** [comment]
We have an issue with the tests failing which I haven't fathomed out yet .. its happening on master too

**Comment by Gadgetoid** [comment]
For testing purposes I believe this is already covered by `assert_invalid_dimensions`  in the `sh1106` tests:

https://github.com/rm-hull/luma.oled/blob/e1388e9562338833ebc6ced571b97b08885e3bef/tests/test_sh1106.py#L41-L46

While it may be possible to iterate supported resolutions and test them by instantiating a device, I don't believe you would gain anything meaningful out of this without observing the result on actual hardware.

That said, if you can introspect the register data from your mocked serial transport then it would be possible to capture a "correct" output (observed on real hardware) and store this in a test that could be useful for catching regressions- IE: compare a real capture of register data sent to real hardware, with a human-verified correct image, and store this for comparison against whatever is sent to the serial transport by the library.

I have updated CONTRIBUTING.rst as requested.

**Comment by thijstriemstra** [comment]
> I don't believe you would gain anything meaningful out of this without observing the result on actual hardware.

Agreed but we want to catch typos, syntax errors etc as well.

**Comment by thijstriemstra** [comment]
> We have an issue with the tests failing which I haven't fathomed out yet .. its happening on master too

I can reproduce it locally as well. I'll take a look.

**Comment by thijstriemstra** [comment]
Please note that #214 was opened to fix the failing tests issue (with Pillow 5.2.0 only) and that should probably land first. If you have any ideas what changed in Pillow, I'm all ears.

**Comment by thijstriemstra** [comment]
#214 is fixed. @Gadgetoid see https://travis-ci.org/rm-hull/luma.oled/jobs/408290417#L585

**Comment by rm-hull** [comment]
@Gadgetoid the build is quite strict about PEP8 compliance, see: https://travis-ci.org/rm-hull/luma.oled/jobs/408290417#L585

You should run `tox` (or at least install and run `flake8`)

**Comment by rm-hull** [comment]
Luma.OLED v2.5.0 released with this driver bundled

**Pull request merged**
