### PR TITLE
doc: add sh1107

### PR DESCRIPTION
**Pull request by thijstriemstra**
@rm-hull can you also add sh1107 to the github repo  description?

### CODE REVIEW

**Comment by thijstriemstra** [comment]
ping @rm-hull

**Comment by thijstriemstra** [comment]
ping @rm-hull

**Comment by thijstriemstra** [comment]
@rm-hull is it possible I do not have to open a pull request for changes like this? I 'ping-ed' you several times but I'd rather not bother you with prs like this and have permission to make a change.

**Comment by rm-hull** [comment]
I'm not sure what permissions I'd need to change. You are down as a collaborator (there is no other option, eg moderator). There are branch rules on master that need one approval, which applies to me too (although as the owner, I can override).

One issue that happens a lot is that notifications get swallowed as spam. I keep unmarking them but Google thinks it knows better.

Maybe another option is to create an organisation and move the projects ownership, and make you a project co-owner?

**Comment by rm-hull** [comment]
In the meantime, I'll approve... Apologies

**Review by rm-hull — APPROVED** [review]

**Pull request merged**
