### PR TITLE
added x32 and x64 options to sh1106

### PR DESCRIPTION
**Pull request by VxGeeks**
added x32 and x64 options to sh1106 and error for "None" setting

### CODE REVIEW

**Comment by thijstriemstra** [comment]
@VxGeeks thanks! But you removed the original `width = 128` support, can you also add that in the list?

**Comment by VxGeeks** [comment]
It didn't seem like we would need it for now, since the only settings we changed were the start-line and multiplex ratio.

**Comment by thijstriemstra** [comment]
@VxGeeks and add yourself to the contributor list in CONTRIBUTING.rst

**Comment by rm-hull** [comment]
@VxGeeks - v2.2.10 published on PyPi with your changes

**Pull request merged**
