### PR TITLE
Support for SSD1327

### PR DESCRIPTION
**Pull request by sharkusk**
This adds support for the SSD1327.  Tested using a 1.5" 128x128 4-bit OLED module built by Waveshare using the SPI interface.  I blatantly copy/pasted the ssd1325 code, only the settings needed to be modified.  I believe there is also a 64x64 display using this controller, but I don't have it for testing purposes.

### CODE REVIEW

**Comment by thijstriemstra** [comment]
Thanks @sharkusk. Can you also add (copy/paste) some tests for this device? Since the coverage dropped with 10%: https://coveralls.io/builds/16156801/source?filename=luma%2Foled%2Fdevice.py#L677

**Comment by rm-hull** [comment]
Yes, happy to accept the PR, but some copy/pasted regression tests would be good though. 

I might try a bit of consolidation after this is merged so that there is more shared common code amongst the devices, eg. the ssd1322, ssd1325 and this ssd1327 could all share a common greyscale superclass, while the ss1331 and ssd1351 inherit from a color superclass

**Comment by sharkusk** [comment]
Okay, test copied and added.  I have no idea how to run the test locally, so I abused the system to get it done.

**Comment by thijstriemstra** [comment]
> I have no idea how to run the test locally, so I abused the system to get it done.

After cloning the repository:


```
sudo pip install tox
```

And run tox:

```
tox -e py27
```

or for py3.4

```
tox -e py34
```

**Comment by thijstriemstra** [comment]
Thanks for the fixes. The class also needs a `.. versionadded:: x.x.x` marker.

**Comment by rm-hull** [comment]
I’ll add the versionadded marker

**Comment by thijstriemstra** [comment]
@rm-hull cool, there's also a reference missing in doc/intro.rst first paragraph.

**Comment by rm-hull** [comment]
thx, will add it :+1:

**Comment by thijstriemstra** [comment]
@rm-hull can you make a new release for this?

**Comment by rm-hull** [comment]
Will be Sunday at the earliest; away on holiday ATM. Is there anything else on #203 that needs doing or can these both be released together?

**Comment by thijstriemstra** [comment]
@rm-hull I would add this change to 2.x series and any larger changes like #203 in 3.x.

**Comment by thijstriemstra** [comment]
ping @rm-hull

**Comment by rm-hull** [comment]
2.4.0 released

**Pull request merged**
