### PR TITLE
release: 3.14.0

### PR DESCRIPTION
**Pull request by thijstriemstra**

### CODE REVIEW

**Review by rm-hull — APPROVED** [review]

**Comment by thijstriemstra** [comment]
@rm-hull after tagging 3.14.0 the pypi publish failed with https://github.com/rm-hull/luma.oled/actions/runs/11585613951/job/32254828557#step:7:22

could you enable trusted publisher for pypi following these steps https://docs.pypi.org/trusted-publishers/adding-a-publisher/#github-actions @rm-hull? Same applies to luma.emulator and all other projects..

**Comment by thijstriemstra** [comment]
@rm-hull I now realize I'm also a maintainer on pypi so I'll give it a try as well

**Comment by thijstriemstra** [comment]
@rm-hull I can;t change the settings cause the "manage" button isn't active, even though the project is in my list.

afbeelding

Could you either give me the permissions to manage luma projects on pypi or take a look yourself at this publishing issue?

**Comment by rm-hull** [comment]
Just looking into this now… will let you know shortly

**Comment by rm-hull** [comment]
you dont seem to be added to the test.pypi.org projects, but i get this when i try to add you:
Screenshot 2024-11-02 at 23 19 37

**Comment by rm-hull** [comment]
> @rm-hull after tagging 3.14.0 the pypi publish failed with https://github.com/rm-hull/luma.oled/actions/runs/11585613951/job/32254828557#step:7:22
> 
> could you enable trusted publisher for pypi following these steps https://docs.pypi.org/trusted-publishers/adding-a-publisher/#github-actions @rm-hull? Same applies to luma.emulator and all other projects..

Have enabled trusted publisher .. looks like it needs to be done for all project for both pypi and test.pypi

**Comment by rm-hull** [comment]
Success: https://github.com/rm-hull/luma.oled/actions/runs/11585613951

will add to all projects

**Pull request merged**
