### PR TITLE
Fix SSD1322 NHD initialization and encode each pixel as 4bit+4bit identical nibbles

### LINKED ISSUE #353: New Haven 2.7 oled with ssd1322
I’ve been having some issues with the same 2.7 New Haven display. Initially the modified _NHs class seemed to work. But grey ramps were messed up and anitalised text looked seriously wonky. I see that those classes were writing out byte values rather than nibble encoded 4bit / 16 grey levels. After some experimentation it looks very much like there’s something interesting going on here. 

I /think/ every other nibble controls the alternate scan of the pixel. Very strange. Anyway if I write out data for wxh (rather than wxh/2) and duplicate every pixel into both the upper and lower nibble everything looks great - the ramps now display correctly and text renders as expected - where’s previously values like 240 (prior to send to device) would snap to an incredibly low display value which looks effectively black). 

So sorry to reopen this but I think the nhd init routine / display routines are still wrong for things that aren’t pure black / white. 

00F285F5-B0E5-4D09-A6EB-DA6C0E3E02B2

I will try and tidy up the copious init routine hacks and submit a PR. 

George

_Originally posted by @georgeharker in https://github.com/rm-hull/luma.oled/issues/199#issuecomment-1299382050_

Further investigation of their example arduino code confirms they tie seg 1 and seg 2 together to form the driver for pixel one. Meaning both nibbles should be set to identical values to drive the display at one byte per pixel. See

https://support.newhavendisplay.com/hc/en-us/articles/4413877789591-NHD-2-7-12864WD-with-Arduino

Says 2 seg lines with one com is one pixel.

### PR DESCRIPTION
**Pull request by georgeharker**
Each pixel should be encoded as two adjacent nibbles (2 nibbles per pixel with identical values) corresponding with the 2 SEG + 1 COM design of the NHD based panel, which uses the two SEG per pixel to drive the charge (hence needing two adjacent pixel values in GDRAM to drive them.

Closes #353, #199

### CODE REVIEW

**Comment by georgeharker** [comment]
Ah. Clearly there’s some tests I need to update

**Review by rm-hull — APPROVED** [review]

**Comment by rm-hull** [comment]
Code changes look reasonable, but the regression test data needs regenerating

**Comment by thijstriemstra** [comment]
> the regression test data needs regenerating

@georgeharker this is the code that @rm-hull is referring to: https://github.com/georgeharker/luma.oled/blob/master/tests/test_ssd1322_nhd.py#L103

**Comment by georgeharker** [comment]
> > the regression test data needs regenerating
> 
> @georgeharker this is the code that @rm-hull is referring to: https://github.com/georgeharker/luma.oled/blob/master/tests/test_ssd1322_nhd.py#L103

My read after looking thru the tests was that I needed to uncomment the regen line, run the regen and comment it back out and submit the test data. The PR now has the regenerated test data. But perhaps I missed something. It didn’t look like the test code itself needed changing as it passed after a regen of the data. 

George

**Comment by thijstriemstra** [comment]
👍🏻

**Pull request merged**
