### PR TITLE
Fix failing tests

### PR DESCRIPTION
**Pull request by thijstriemstra**
Tests are failing currently. When downgrading Pillow from 5.2.0 to an older version, the tests succeed again.

```
pip install Pillow==5.0.0
```

@rm-hull is there anything that stands out in the Pillow changelog? https://github.com/python-pillow/Pillow/blob/master/CHANGES.rst#520-2018-07-01

Maybe the `Fixed bug in ImageDraw.multiline_textsize() #3114 [tianyu139]`: https://github.com/python-pillow/Pillow/pull/3114?

### CODE REVIEW

**Comment by thijstriemstra** [comment]
@rm-hull or maybe https://github.com/python-pillow/Pillow/pull/3147? I'm afraid you'll have to look into the details, all I know it's Pillow related.

**Comment by rm-hull** [comment]
@thijstriemstra should we just dial pillow back to 5.0.0 for the time being, just to get things green again and then investigate separately?

**Comment by thijstriemstra** [comment]
> just to get things green again and then investigate separately?

I'd rather not..

**Comment by rm-hull** [comment]
p.s:
* 144 = 0b10010000
* 176 = 0b10110000

So what has _probably_ happened is that the bit pattern for one character maybe had a serif before, but now doesnt !?!?

**Comment by rm-hull** [comment]
I'm guessing it will have been same root cause as https://github.com/rm-hull/luma.core/issues/135, but am puzzled as to why this has only just manifested in the last few weeks

**Comment by rm-hull** [comment]
> Sounds good. Documenting how you regenerate would be useful as well.

In the end, for the larger files where it was using mocking (rather than recording) I just copy/pasted the actual output into the relevant json data file :-/

**Pull request merged**
